name: rnaseq-webinar
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.12
  - fastqc=0.12.1
  - multiqc
  - trimmomatic=0.39
  - hisat2=2.2.3
  - samtools=1.24
  - gffread=0.12.9
  - salmon=1.11.4
  - parallel
  - openjdk=17
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - rich
  - pip
